#!/bin/bash
#
# One chunk of the standard books, turned from photographs into text.
#
# Sangwan and Haralambos are CamScanner scans with no text layer: to a computer
# they are pictures of pages. Until they are read, a model answer can cite them
# but cannot be written from them — which is the wrong way round, because the
# book is the authority and the model is only the thing that shapes it into
# forty marks.
#
# Time-boxed, not page-boxed. A sandboxed command is killed after about three
# minutes and nothing survives it, so this reads as many pages as fit in its
# budget and exits cleanly. Pages already done are skipped, so running it again
# continues exactly where it stopped and a missed run costs a day, not a restart.
# Measured rate is about nine seconds a page: roughly sixteen pages a run.
#
# HEAVIEST CHAPTERS FIRST. tools/sangwan-order.txt lists Sangwan's chapters as
# PDF page ranges, ordered by how much of the last ten years of questions each
# one accounts for. Social Thinkers is thirteen per cent and is read first;
# Politics and Society is one and a half and is read last. Front-to-back order
# would leave the feature useless until the whole book finished; this way it
# starts working for the questions most likely to come up, first.
#
# Output goes to book-text/, which is git-ignored: these are paid books and this
# repository is public. Only this script and the page-count manifest are tracked,
# and the manifest holds counts, never text.

BUDGET=${1:-150}
DEADLINE=$(( $(date +%s) + BUDGET ))
ROOT="$HOME/mnt/sociology-study-tracker"
BOOKS="$ROOT/standard books"
OUT="$ROOT/book-text"
WORK="${TMPDIR:-/tmp}/ocrwork.$$"
mkdir -p "$WORK" "$OUT/sangwan" "$OUT/haralambos"
trap 'rm -rf "$WORK"' EXIT

read_page() {          # book, pdf file, page number
  local name="$1" pdf="$2" p="$3" n img
  n=$(printf %03d "$p")
  [ -s "$OUT/$name/$n.txt" ] && return 0
  [ "$(date +%s)" -ge "$DEADLINE" ] && return 2
  pdftoppm -r 300 -gray -f "$p" -l "$p" -png "$BOOKS/$pdf" "$WORK/pg" 2>/dev/null
  img=$(ls "$WORK"/pg-*.png 2>/dev/null | head -1)
  [ -z "$img" ] && return 0
  # --psm 4 reads this layout best: a single column with variable line spacing.
  tesseract "$img" "$OUT/$name/$n" --psm 4 2>/dev/null
  rm -f "$WORK"/pg-*.png
  return 0
}

SANGWAN_PDF="Seema_Nitin_Sangwan_Essential_Sociology_For_Civil_Services_Main.pdf"
HARALAMBOS_PDF="Haralambos orange book.pdf"

# Sangwan, chapter by chapter, in the order the questions justify.
for range in $(cat "$ROOT/tools/sangwan-order.txt"); do
  for p in $(seq "${range%%-*}" "${range##*-}"); do
    read_page sangwan "$SANGWAN_PDF" "$p" || { out_of_time=1; break 2; }
  done
done

# Then Haralambos, which is a partial scan anyway.
if [ -z "$out_of_time" ]; then
  for p in $(seq 13 380); do
    read_page haralambos "$HARALAMBOS_PDF" "$p" || break
  done
fi

s=$(ls "$OUT/sangwan"/*.txt 2>/dev/null | wc -l)
h=$(ls "$OUT/haralambos"/*.txt 2>/dev/null | wc -l)

# A manifest the app can read. Counts only — no text ever goes in the repo.
cat > "$ROOT/src/data/bookScan.ts" <<TS
/**
 * How much of the scanned books has been read into text so far.
 *
 * Generated by tools/ocr-books.sh — do not edit by hand; the next run will
 * overwrite it. Page counts only. The text itself lives in book-text/, which is
 * git-ignored, because these are paid books and this repository is public.
 *
 * Until this reaches its totals, a model answer is written from the model's own
 * knowledge with the chapters cited beside it, rather than out of the chapters
 * themselves. The app says so rather than letting anyone assume otherwise.
 */
export const BOOK_SCAN = {
  sangwan: { read: $s, total: 445 },
  haralambos: { read: $h, total: 368 },
  updated: "$(date -u +%Y-%m-%d)",
} as const;

export function scanPagesRead(): number {
  return BOOK_SCAN.sangwan.read + BOOK_SCAN.haralambos.read;
}

export function scanPagesTotal(): number {
  return BOOK_SCAN.sangwan.total + BOOK_SCAN.haralambos.total;
}

/** True while a model answer still cannot be written out of the books. */
export function scanPending(): boolean {
  return scanPagesRead() < scanPagesTotal();
}
TS

echo "sangwan $s/445 · haralambos $h/368 · $(( s + h ))/813 pages read"
