/**
 * How much of the scanned books has been read into text so far.
 *
 * Generated by tools/ocr-books.sh — do not edit by hand; the next run will
 * overwrite it. Page counts only. The text itself lives in book-text/, which is
 * git-ignored, because these are paid books and this repository is public.
 *
 * Until this reaches its totals, a model answer is written from the model's own
 * knowledge with the chapters cited beside it, rather than out of the chapters
 * themselves. The app says so rather than letting anyone assume otherwise.
 */
export const BOOK_SCAN = {
  sangwan: { read: 7, total: 445 },
  haralambos: { read: 0, total: 368 },
  updated: "2026-09-01",
} as const;

export function scanPagesRead(): number {
  return BOOK_SCAN.sangwan.read + BOOK_SCAN.haralambos.read;
}

export function scanPagesTotal(): number {
  return BOOK_SCAN.sangwan.total + BOOK_SCAN.haralambos.total;
}

/** True while a model answer still cannot be written out of the books. */
export function scanPending(): boolean {
  return scanPagesRead() < scanPagesTotal();
}
